
name: Atualizar data.json diariamente

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install node-fetch@2

      - name: Criar config.json
        run: |
          echo '{"apiKey":"${{ secrets.YT_API_KEY }}","channelId":"${{ secrets.YT_CHANNEL_ID }}"}' > config.json

      - name: Rodar geraData.js
        run: node geraData.js

      - name: Commit e Push data.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Atualiza data.json automaticamente"
          git push
